language: csharp
solution: ./src/Dagmatic.Akka.sln

env:
  global:
    BUILD_CONFIG=Release
    XUNIT_RUNNER_V=2.3.0-beta1-build3642
        

install:
  - nuget restore ./src/Dagmatic.Akka.sln
  - nuget install xunit.runner.console -Version ${XUNIT_RUNNER_V} -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=${BUILD_CONFIG} ./src/Dagmatic.Akka.sln
  - mono ./testrunner/xunit.runner.console.${XUNIT_RUNNER_V}/tools/xunit.console.exe ./src/Actor.Tests/bin/${BUILD_CONFIG}/Dagmatic.Akka.Actor.Tests.dll
